// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCredentials() {
  return window['go']['main']['App']['GetCredentials']();
}

export function GetImageName() {
  return window['go']['main']['App']['GetImageName']();
}

export function HealthCheck() {
  return window['go']['main']['App']['HealthCheck']();
}

export function IsContainerReady() {
  return window['go']['main']['App']['IsContainerReady']();
}

export function OpenBrowser() {
  return window['go']['main']['App']['OpenBrowser']();
}

export function RunMoodle() {
  return window['go']['main']['App']['RunMoodle']();
}

export function StopMoodle() {
  return window['go']['main']['App']['StopMoodle']();
}
