// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCredentials():Promise<Record<string, string>>;

export function GetImageName():Promise<string>;

export function HealthCheck():Promise<Record<string, boolean>>;

export function IsContainerReady():Promise<boolean>;

export function OpenBrowser():Promise<void>;

export function RunMoodle():Promise<void>;

export function StopMoodle():Promise<void>;
